application: your-app
version: 1

runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: public/static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
